- name: anti-hasselhoff
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install fswebcam
    apt: name="{{packages}}" state=present
    vars:
      packages:
      - fswebcam
      - xdotool
    become: true

  - name: Install logkeys
    apt:
      deb: dependencies/logkeys_0.1.1c-1_amd64.deb
    become: true

  - name: Install script in bin
    copy:
      src: anti-hasselhoff.sh
      dest: /usr/local/bin/anti-hasselhoff
      mode: '0755'
    become: true